#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#logout:
#    path: /logout
logout:
    path:
        #en: /logout
        pl: /wyloguj

#login:
#    path:
#        en: /login
#        pl: /logowanie


#homepage:
#    path: /
#    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
#    defaults:
        #path: search_list
        #path: /wyszukiwania/lista
        #path:
        #    en: /search/list
        #    pl: /wyszukiwania/lista
#        route: search_list
#        permanent: true